#!/bin/bash
export SSHOPT="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "

ssh $SSHOPT -i ~/.ec2/sandbox.pem ubuntu@sandbox.activestate.com "sudo cp /home/stackato/stackato/vcap/cloud_controller/db/cloudcontroller.sqlite3 /tmp/; sudo chown \$USER /tmp/cloudcontroller.sqlite3"
mkdir -p tmp
scp $SSHOPT -i ~/.ec2/sandbox.pem ubuntu@sandbox.activestate.com:/tmp/cloudcontroller.sqlite3 tmp/sandbox-cc.db

