#!/bin/bash
# Print the hostnames of running DEAs

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
    export JAVA_HOME=/usr/lib/jvm/java-6-openjdk
else
    export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home 
fi

export EC2_HOME=$HOME/Downloads/ec2-api-tools-1.4.4.2
export EC2_CERT=`ls ~/.ec2/cert-*.pem`
export EC2_PRIVATE_KEY=`ls ~/.ec2/pk-*.pem`
export SSHCMD="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "

export DEA_AMI_ID=`$SSHCMD -i ~/.ec2/sandbox.pem ubuntu@sandbox.activestate.com cat /home/stackato/.sandbox_config  | grep ami\: | cut -d" " -f 2 | cut -d'"' -f2`

$EC2_HOME/bin/ec2-describe-instances | grep $DEA_AMI_ID | grep running | cut -f 4
