#!/bin/bash
# Tails dea.log of the given host
export SSHCMD="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "

$SSHCMD -i ~/.ec2/sandbox.pem ubuntu@$1 'grep -v "to execute du"  /tmp/vcap-run/dea.log  | grep -v "received router start message" | grep -v "to process ps and du" | tail -f -n 200 '
