#!/bin/bash
set -x

git submodule update

# build clojurescript with patches applied
pushd dev/clojurescript
echo "Patching the bootstrap script to use closure library from svn HEAD"
patch -R -p1 < ../use-closure-library-HEAD.patch
script/bootstrap
popd

# install project dependencies
lein deps

# install sass (and foreman) as last step, as it may fail if rubygems
# is not installed or if the user has no sudo access.
sudo gem install --no-ri --no-rdoc sass foreman
