#!/bin/bash
set -e -x

git submodule update

unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
    # these are required to build clojurescript on ubuntu
    sudo apt-get install -y curl subversion openjdk-6-jdk
fi

# build clojurescript with patches applied
pushd dev/clojurescript
echo "Patching the bootstrap script to use closure library from svn HEAD"
patch -N -p1 < ../use-closure-library-HEAD.patch
script/bootstrap
popd

# install sass and foreman
if [[ "$unamestr" == 'Linux' ]]; then
    echo "This assumes that you have ruby installed via RVM."
    echo "Ubuntu's ruby packages are broken."
    echo "See http://ryanbigg.com/2010/12/ubuntu-ruby-rvm-rails-and-you/"
    gem install --no-ri --no-rdoc sass foreman
else
    sudo gem install --no-ri --no-rdoc sass foreman
fi

# install project dependencies
dev/lein deps
