#!/bin/sh
# Tails dea.log of the given host
export SSHCMD="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no "

$SSHCMD -i ~/.ec2/sandbox.pem ubuntu@$1 tail -n 1000 -f /tmp/vcap-run/dea.log
